#! /bin/sh
#
# Based on catalina.sh from Tomcat7
# Author: Thomas Bocek

start ()
{
  if [ "$1" = "fg" ]; then
    echo "xdocc starting in foreground with debugging options enabled..."
    java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n -Duser.dir=/usr/lib/xdocc -jar /usr/lib/xdocc/xdocc*.jar -f -c /etc/xdocc/ -s /var/lib/xdocc/xdocc.mapdb
    exit 0;
  fi

  if [ -r /var/run/xdocc.pid -a -s /var/run/xdocc.pid ]; then
    PID=`cat /var/run/xdocc.pid`
    ps -p $PID >/dev/null 2>&1
    if [ $? -eq 0 ] ; then
      echo "xdocc appears to still be running with PID $PID. Start aborted."
      exit 1
    else
      echo "Removing/clearing stale PID file."
      rm -f /var/run/xdocc.pid >/dev/null 2>&1
      if [ $? != 0 ]; then
        if [ -w /var/run/xdocc.pid ]; then
          cat /dev/null > /var/run/xdocc.pid
        else
          echo "Unable to remove or clear stale PID file. Start aborted."
          exit 1
        fi
      fi
    fi
  fi
  #now start the application
  nohup java -Duser.dir=/usr/lib/xdocc -jar /usr/lib/xdocc/xdocc*.jar -f -c /etc/xdocc/ -s /var/lib/xdocc/xdocc.mapdb < /dev/null > /var/log/xdocc/output.log 2>&1 &
  echo $! > /var/run/xdocc.pid
  echo "xdocc started ..."
}

stop ()
{
  if [ -r /var/run/xdocc.pid -a -s /var/run/xdocc.pid ]; then
    PID=`cat /var/run/xdocc.pid`
    echo "Stopping xdocc ..."
    SLEEP=5
    while [ $SLEEP -ge 0 ]; do
      kill -0 $PID >/dev/null 2>&1
      if [ $? -gt 0 ]; then
        rm -f /var/run/xdocc.pid >/dev/null 2>&1
        if [ $? != 0 ]; then
          if [ -w /var/run/xdocc.pid ]; then
            cat /dev/null > /var/run/xdocc.pid
          else
            echo "The PID file could not be removed or cleared."
          fi
        fi
        echo "xdocc stopped."
        break
      fi
      if [ $SLEEP -gt 0 ]; then
        sleep 1
      fi
      if [ $SLEEP -eq 0 ]; then
        echo "xdocc did not stop in time. PID file was not removed. You may need to kill it manually."
      fi
      SLEEP=`expr $SLEEP - 1 `
    done
  else
    echo "xdocc is not running ..."
  fi
}

case "$1" in
  start)
    start $2
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: /etc/init.d/xdocc {start|stop}"
    exit 1
    ;;
esac

exit 0