#!/bin/sh
# preinst script for xdocc

systemctl is-active --quiet xdocc.service && systemctl stop xdocc.service

mkdir -p /var/log/xdocc
mkdir -p /var/lib/xdocc
mkdir -p /var/www/example-xdocc

rm -f /var/lib/xdocc/xdocc.mapdb*